window.AnimalTypingRuntimeConfig = {
  "version": "1.1.0",
  "storageNamespace": "animalTyping.v1",
  "historyLimit": 100,
  "rollingWpmSeconds": 10,
  "animalTierStabilitySeconds": 3,
  "autoPauseOnBlur": true,
  "timedDurations": [
    30,
    60,
    120
  ],
  "lessonSets": [
    {
      "id": "course-80",
      "name": "80-Lesson Course"
    }
  ],
  "keyboardLayouts": [
    "qwerty-us"
  ],
  "defaults": {
    "playerName": "Player 1",
    "lessonSet": "course-80",
    "lessonId": "course-80-01",
    "patternIndex": 0,
    "keyboardLayout": "qwerty-us",
    "sceneBackground": "meadow",
    "showKeyboard": true,
    "showFingerGuide": true,
    "sound": true,
    "keyClickSound": false,
    "reducedMotion": false,
    "showNextKeyHint": true,
    "allowOnScreenKeyTap": false
  },
  "animalTiers": [
    {
      "id": "snail",
      "name": "Snail",
      "minEffectiveWpm": 0,
      "minAccuracy": 0,
      "asset": "assets/animals/snail-v2.svg",
      "movementMultiplier": 0.45
    },
    {
      "id": "turtle",
      "name": "Turtle",
      "minEffectiveWpm": 8,
      "minAccuracy": 75,
      "asset": "assets/animals/turtle-v2.svg",
      "movementMultiplier": 0.65
    },
    {
      "id": "rabbit",
      "name": "Rabbit",
      "minEffectiveWpm": 18,
      "minAccuracy": 85,
      "asset": "assets/animals/rabbit-v2.svg",
      "movementMultiplier": 0.85
    },
    {
      "id": "horse",
      "name": "Horse",
      "minEffectiveWpm": 30,
      "minAccuracy": 90,
      "asset": "assets/animals/horse-v2.svg",
      "movementMultiplier": 1
    },
    {
      "id": "cheetah",
      "name": "Cheetah",
      "minEffectiveWpm": 45,
      "minAccuracy": 95,
      "asset": "assets/animals/cheetah-v2.svg",
      "movementMultiplier": 1.2
    }
  ],
  "audio": {
    "correct": "assets/audio/correct.wav",
    "wrong": "assets/audio/wrong.wav",
    "tier": "assets/audio/tier.wav",
    "complete": "assets/audio/complete.wav"
  },
  "backgrounds": [
    {
      "id": "meadow",
      "name": "Sunny Meadow",
      "asset": "assets/backgrounds/meadow.svg"
    }
  ],
  "keyboardLayoutDefinitions": {
    "qwerty-us": {
      "id": "qwerty-us",
      "name": "QWERTY US",
      "rows": [
        [
          {
            "code": "Backquote",
            "label": "`",
            "shift": "~",
            "finger": "left-pinky"
          },
          {
            "code": "Digit1",
            "label": "1",
            "shift": "!",
            "finger": "left-pinky"
          },
          {
            "code": "Digit2",
            "label": "2",
            "shift": "@",
            "finger": "left-ring"
          },
          {
            "code": "Digit3",
            "label": "3",
            "shift": "#",
            "finger": "left-middle"
          },
          {
            "code": "Digit4",
            "label": "4",
            "shift": "$",
            "finger": "left-index"
          },
          {
            "code": "Digit5",
            "label": "5",
            "shift": "%",
            "finger": "left-index"
          },
          {
            "code": "Digit6",
            "label": "6",
            "shift": "^",
            "finger": "right-index"
          },
          {
            "code": "Digit7",
            "label": "7",
            "shift": "&",
            "finger": "right-index"
          },
          {
            "code": "Digit8",
            "label": "8",
            "shift": "*",
            "finger": "right-middle"
          },
          {
            "code": "Digit9",
            "label": "9",
            "shift": "(",
            "finger": "right-ring"
          },
          {
            "code": "Digit0",
            "label": "0",
            "shift": ")",
            "finger": "right-pinky"
          },
          {
            "code": "Minus",
            "label": "-",
            "shift": "_",
            "finger": "right-pinky"
          },
          {
            "code": "Equal",
            "label": "=",
            "shift": "+",
            "finger": "right-pinky"
          },
          {
            "code": "Backspace",
            "label": "Backspace",
            "special": true,
            "finger": "right-pinky",
            "wide": 2
          }
        ],
        [
          {
            "code": "Tab",
            "label": "Tab",
            "special": true,
            "finger": "left-pinky",
            "wide": 1.5
          },
          {
            "code": "KeyQ",
            "label": "q",
            "shift": "Q",
            "finger": "left-pinky"
          },
          {
            "code": "KeyW",
            "label": "w",
            "shift": "W",
            "finger": "left-ring"
          },
          {
            "code": "KeyE",
            "label": "e",
            "shift": "E",
            "finger": "left-middle"
          },
          {
            "code": "KeyR",
            "label": "r",
            "shift": "R",
            "finger": "left-index"
          },
          {
            "code": "KeyT",
            "label": "t",
            "shift": "T",
            "finger": "left-index"
          },
          {
            "code": "KeyY",
            "label": "y",
            "shift": "Y",
            "finger": "right-index"
          },
          {
            "code": "KeyU",
            "label": "u",
            "shift": "U",
            "finger": "right-index"
          },
          {
            "code": "KeyI",
            "label": "i",
            "shift": "I",
            "finger": "right-middle"
          },
          {
            "code": "KeyO",
            "label": "o",
            "shift": "O",
            "finger": "right-ring"
          },
          {
            "code": "KeyP",
            "label": "p",
            "shift": "P",
            "finger": "right-pinky"
          },
          {
            "code": "BracketLeft",
            "label": "[",
            "shift": "{",
            "finger": "right-pinky"
          },
          {
            "code": "BracketRight",
            "label": "]",
            "shift": "}",
            "finger": "right-pinky"
          },
          {
            "code": "Backslash",
            "label": "\\",
            "shift": "|",
            "finger": "right-pinky",
            "wide": 1.4
          }
        ],
        [
          {
            "code": "CapsLock",
            "label": "Caps",
            "special": true,
            "finger": "left-pinky",
            "wide": 1.8
          },
          {
            "code": "KeyA",
            "label": "a",
            "shift": "A",
            "finger": "left-pinky"
          },
          {
            "code": "KeyS",
            "label": "s",
            "shift": "S",
            "finger": "left-ring"
          },
          {
            "code": "KeyD",
            "label": "d",
            "shift": "D",
            "finger": "left-middle"
          },
          {
            "code": "KeyF",
            "label": "f",
            "shift": "F",
            "finger": "left-index",
            "anchor": true
          },
          {
            "code": "KeyG",
            "label": "g",
            "shift": "G",
            "finger": "left-index"
          },
          {
            "code": "KeyH",
            "label": "h",
            "shift": "H",
            "finger": "right-index"
          },
          {
            "code": "KeyJ",
            "label": "j",
            "shift": "J",
            "finger": "right-index",
            "anchor": true
          },
          {
            "code": "KeyK",
            "label": "k",
            "shift": "K",
            "finger": "right-middle"
          },
          {
            "code": "KeyL",
            "label": "l",
            "shift": "L",
            "finger": "right-ring"
          },
          {
            "code": "Semicolon",
            "label": ";",
            "shift": ":",
            "finger": "right-pinky"
          },
          {
            "code": "Quote",
            "label": "'",
            "shift": "\"",
            "finger": "right-pinky"
          },
          {
            "code": "Enter",
            "label": "Enter",
            "special": true,
            "finger": "right-pinky",
            "wide": 2.2
          }
        ],
        [
          {
            "code": "ShiftLeft",
            "label": "Shift",
            "special": true,
            "finger": "left-pinky",
            "wide": 2.3
          },
          {
            "code": "KeyZ",
            "label": "z",
            "shift": "Z",
            "finger": "left-pinky"
          },
          {
            "code": "KeyX",
            "label": "x",
            "shift": "X",
            "finger": "left-ring"
          },
          {
            "code": "KeyC",
            "label": "c",
            "shift": "C",
            "finger": "left-middle"
          },
          {
            "code": "KeyV",
            "label": "v",
            "shift": "V",
            "finger": "left-index"
          },
          {
            "code": "KeyB",
            "label": "b",
            "shift": "B",
            "finger": "left-index"
          },
          {
            "code": "KeyN",
            "label": "n",
            "shift": "N",
            "finger": "right-index"
          },
          {
            "code": "KeyM",
            "label": "m",
            "shift": "M",
            "finger": "right-index"
          },
          {
            "code": "Comma",
            "label": ",",
            "shift": "<",
            "finger": "right-middle"
          },
          {
            "code": "Period",
            "label": ".",
            "shift": ">",
            "finger": "right-ring"
          },
          {
            "code": "Slash",
            "label": "/",
            "shift": "?",
            "finger": "right-pinky"
          },
          {
            "code": "ShiftRight",
            "label": "Shift",
            "special": true,
            "finger": "right-pinky",
            "wide": 2.6
          }
        ],
        [
          {
            "code": "Space",
            "label": "Space",
            "special": true,
            "finger": "thumbs",
            "wide": 8
          }
        ]
      ]
    }
  },
  "lessons": [
    {
      "id": "course-80-01",
      "title": "1. F & J Anchor Keys",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "f",
        "j"
      ],
      "difficulty": "beginner",
      "text": "fj jf fj jf fj jf fj jf fj jf fj jf fj jf fj jf",
      "patterns": [
        "fj jf fj jf fj jf fj jf fj jf fj jf fj jf fj jf",
        "ff jj ff jj ff jj ff jj ff jj ff jj ff jj ff jj",
        "fjfj jfjf fjfj jfjf fjfj jfjf fjfj jfjf fjfj jfjf fjfj jfjf",
        "jf fj jf fj jf fj jf fj jf fj jf fj jf fj jf fj",
        "fff jjj fff jjj fff jjj fff jjj fff jjj fff jjj fff jjj"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-02",
      "title": "2. D & K Reach",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "d",
        "k",
        "f",
        "j"
      ],
      "difficulty": "beginner",
      "text": "dk kd dk kd dk kd dk kd dk kd dk kd dk kd dk kd",
      "patterns": [
        "dk kd dk kd dk kd dk kd dk kd dk kd dk kd dk kd",
        "df jk df jk df jk df jk df jk df jk df jk df jk",
        "dkdk kdkd dkdk kdkd dkdk kdkd dkdk kdkd dkdk kdkd dkdk kdkd",
        "fd jk fd jk fd jk fd jk fd jk fd jk fd jk fd jk",
        "dd kk dd kk dd kk dd kk dd kk dd kk dd kk dd kk"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-03",
      "title": "3. S & L Reach",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "s",
        "l",
        "d",
        "k",
        "f",
        "j"
      ],
      "difficulty": "beginner",
      "text": "sl ls sl ls sl ls sl ls sl ls sl ls sl ls sl ls",
      "patterns": [
        "sl ls sl ls sl ls sl ls sl ls sl ls sl ls sl ls",
        "sd kl sd kl sd kl sd kl sd kl sd kl sd kl sd kl",
        "slsl lsls slsl lsls slsl lsls slsl lsls slsl lsls slsl lsls",
        "fs jl fs jl fs jl fs jl fs jl fs jl fs jl fs jl",
        "ss ll ss ll ss ll ss ll ss ll ss ll ss ll ss ll"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-04",
      "title": "4. A & ; Outer Keys",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "a",
        ";",
        "s",
        "l",
        "f",
        "j"
      ],
      "difficulty": "beginner",
      "text": "a; ;a a; ;a a; ;a a; ;a a; ;a a; ;a a; ;a a; ;a",
      "patterns": [
        "a; ;a a; ;a a; ;a a; ;a a; ;a a; ;a a; ;a a; ;a",
        "as l; as l; as l; as l; as l; as l; as l; as l;",
        "a;a; ;a;a a;a; ;a;a a;a; ;a;a a;a; ;a;a a;a; ;a;a a;a; ;a;a",
        "fa j; fa j; fa j; fa j; fa j; fa j; fa j; fa j;",
        "aa ;; aa ;; aa ;; aa ;; aa ;; aa ;; aa ;; aa ;;"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-05",
      "title": "5. Left Hand ASDF",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "a",
        "s",
        "d",
        "f"
      ],
      "difficulty": "beginner",
      "text": "asdf fdsa asdf fdsa asdf fdsa asdf fdsa asdf fdsa asdf fdsa",
      "patterns": [
        "asdf fdsa asdf fdsa asdf fdsa asdf fdsa asdf fdsa asdf fdsa",
        "adsf sfda adsf sfda adsf sfda adsf sfda adsf sfda adsf sfda",
        "sdfa fasd sdfa fasd sdfa fasd sdfa fasd sdfa fasd sdfa fasd",
        "fdas dsaf fdas dsaf fdas dsaf fdas dsaf fdas dsaf fdas dsaf",
        "asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-06",
      "title": "6. Right Hand JKL;",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "j",
        "k",
        "l",
        ";"
      ],
      "difficulty": "beginner",
      "text": "jkl; ;lkj jkl; ;lkj jkl; ;lkj jkl; ;lkj jkl; ;lkj jkl; ;lkj",
      "patterns": [
        "jkl; ;lkj jkl; ;lkj jkl; ;lkj jkl; ;lkj jkl; ;lkj jkl; ;lkj",
        "jklj kl;k jklj kl;k jklj kl;k jklj kl;k jklj kl;k jklj kl;k",
        "lkjl kj;l lkjl kj;l lkjl kj;l lkjl kj;l lkjl kj;l lkjl kj;l",
        ";jkl jkl; ;jkl jkl; ;jkl jkl; ;jkl jkl; ;jkl jkl; ;jkl jkl;",
        "jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl;"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-07",
      "title": "7. Cross-Hand Pairs",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "a",
        "j",
        "s",
        "k",
        "d",
        "l",
        "f",
        ";"
      ],
      "difficulty": "beginner",
      "text": "aj sk dl f; aj sk dl f; aj sk dl f; aj sk dl f; aj sk dl f;",
      "patterns": [
        "aj sk dl f; aj sk dl f; aj sk dl f; aj sk dl f; aj sk dl f;",
        "ja ks ld ;f ja ks ld ;f ja ks ld ;f ja ks ld ;f ja ks ld ;f",
        "ak sj df l; ak sj df l; ak sj df l; ak sj df l; ak sj df l;",
        "as jk dl f; as jk dl f; as jk dl f; as jk dl f; as jk dl f;",
        "af jl sd k; af jl sd k; af jl sd k; af jl sd k; af jl sd k;"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-08",
      "title": "8. Full Home Row Flow",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "a",
        "s",
        "d",
        "f",
        "j",
        "k",
        "l",
        ";"
      ],
      "difficulty": "beginner",
      "text": "asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl;",
      "patterns": [
        "asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl; asdf jkl;",
        "fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj",
        "asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj asdf ;lkj",
        "fjdksla; fjdksla; fjdksla; fjdksla; fjdksla; fjdksla;",
        "asj dkf l; asj dkf l; asj dkf l; asj dkf l; asj dkf l;"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-09",
      "title": "9. Home Row Alternation",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "f",
        "j",
        "d",
        "k",
        "s",
        "l",
        "a",
        ";"
      ],
      "difficulty": "beginner",
      "text": "fj dk sl a; fj dk sl a; fj dk sl a; fj dk sl a; fj dk sl a;",
      "patterns": [
        "fj dk sl a; fj dk sl a; fj dk sl a; fj dk sl a; fj dk sl a;",
        "jf kd ls ;a jf kd ls ;a jf kd ls ;a jf kd ls ;a jf kd ls ;a",
        "fs jd ak l; fs jd ak l; fs jd ak l; fs jd ak l; fs jd ak l;",
        "aj sk dl f; aj sk dl f; aj sk dl f; aj sk dl f; aj sk dl f;",
        "fa js dk l; fa js dk l; fa js dk l; fa js dk l; fa js dk l;"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-10",
      "title": "10. Home Row Repetition",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "a",
        "s",
        "d",
        "f",
        "j",
        "k",
        "l",
        ";"
      ],
      "difficulty": "beginner",
      "text": "aaa sss ddd fff aaa sss ddd fff aaa sss ddd fff aaa sss ddd fff",
      "patterns": [
        "aaa sss ddd fff aaa sss ddd fff aaa sss ddd fff aaa sss ddd fff",
        "jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;;",
        "asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf",
        "jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl;",
        "fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj fdsa ;lkj"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-11",
      "title": "11. Home Row Mini Words",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "s",
        "a",
        "d",
        "f",
        "l",
        "k",
        "j",
        "z"
      ],
      "difficulty": "beginner",
      "text": "sad dad fall ask sad dad fall ask sad dad fall ask sad dad fall ask",
      "patterns": [
        "sad dad fall ask sad dad fall ask sad dad fall ask sad dad fall ask",
        "all lad flask all lad flask all lad flask all lad flask",
        "jazz lass dad jazz lass dad jazz lass dad jazz lass dad",
        "salad fall ask salad fall ask salad fall ask salad fall ask",
        "add fad lass add fad lass add fad lass add fad lass add fad lass"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-12",
      "title": "12. Home Row Speed Control",
      "lessonSet": "course-80",
      "section": "Home Row",
      "targetKeys": [
        "a",
        "s",
        "d",
        "f",
        "j",
        "k",
        "l",
        ";"
      ],
      "difficulty": "beginner",
      "text": "asdf jkl; fj dk asdf jkl; fj dk asdf jkl; fj dk asdf jkl; fj dk",
      "patterns": [
        "asdf jkl; fj dk asdf jkl; fj dk asdf jkl; fj dk asdf jkl; fj dk",
        "fdsa ;lkj jf kd fdsa ;lkj jf kd fdsa ;lkj jf kd fdsa ;lkj jf kd",
        "as df jk l; as df jk l; as df jk l; as df jk l; as df jk l;",
        "fj fj dk dk sl sl fj fj dk dk sl sl fj fj dk dk sl sl fj fj dk dk sl sl",
        "a; a; sk sk dl dl a; a; sk sk dl dl a; a; sk sk dl dl a; a; sk sk dl dl"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Home Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-13",
      "title": "13. E & I Anchor Pair",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "e",
        "i",
        "r"
      ],
      "difficulty": "beginner",
      "text": "ei ie ei ie ei ie ei ie ei ie ei ie ei ie ei ie",
      "patterns": [
        "ei ie ei ie ei ie ei ie ei ie ei ie ei ie ei ie",
        "ee ii ee ii ee ii ee ii ee ii ee ii ee ii ee ii",
        "eiei ieie eiei ieie eiei ieie eiei ieie eiei ieie eiei ieie",
        "erie irei erie irei erie irei erie irei erie irei erie irei",
        "ei ei ei ei ei ei ei ei ei ei ei ei ei ei ei ei"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-14",
      "title": "14. R & U Reach",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "r",
        "u",
        "e",
        "i"
      ],
      "difficulty": "beginner",
      "text": "ru ur ru ur ru ur ru ur ru ur ru ur ru ur ru ur",
      "patterns": [
        "ru ur ru ur ru ur ru ur ru ur ru ur ru ur ru ur",
        "rr uu rr uu rr uu rr uu rr uu rr uu rr uu rr uu",
        "ruru urur ruru urur ruru urur ruru urur ruru urur ruru urur",
        "eru rui eru rui eru rui eru rui eru rui eru rui eru rui",
        "ru ru ru ru ru ru ru ru ru ru ru ru ru ru ru ru"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-15",
      "title": "15. W & O Reach",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "w",
        "o",
        "e",
        "i",
        "r"
      ],
      "difficulty": "beginner",
      "text": "wo ow wo ow wo ow wo ow wo ow wo ow wo ow wo ow",
      "patterns": [
        "wo ow wo ow wo ow wo ow wo ow wo ow wo ow wo ow",
        "ww oo ww oo ww oo ww oo ww oo ww oo ww oo ww oo",
        "wowo owow wowo owow wowo owow wowo owow wowo owow wowo owow",
        "weio row weio row weio row weio row weio row weio row",
        "wo wo wo wo wo wo wo wo wo wo wo wo wo wo wo wo"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-16",
      "title": "16. Q & P Outer Keys",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "q",
        "p",
        "w",
        "e",
        "r",
        "o",
        "i",
        "u"
      ],
      "difficulty": "beginner",
      "text": "qp pq qp pq qp pq qp pq qp pq qp pq qp pq qp pq",
      "patterns": [
        "qp pq qp pq qp pq qp pq qp pq qp pq qp pq qp pq",
        "qq pp qq pp qq pp qq pp qq pp qq pp qq pp qq pp",
        "qpqp pqpq qpqp pqpq qpqp pqpq qpqp pqpq qpqp pqpq qpqp pqpq",
        "qwer poiu qwer poiu qwer poiu qwer poiu qwer poiu qwer poiu",
        "qp qp qp qp qp qp qp qp qp qp qp qp qp qp qp qp"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-17",
      "title": "17. T & Y Center Keys",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "t",
        "y",
        "r",
        "e"
      ],
      "difficulty": "beginner",
      "text": "ty yt ty yt ty yt ty yt ty yt ty yt ty yt ty yt",
      "patterns": [
        "ty yt ty yt ty yt ty yt ty yt ty yt ty yt ty yt",
        "tt yy tt yy tt yy tt yy tt yy tt yy tt yy tt yy",
        "tyty ytyt tyty ytyt tyty ytyt tyty ytyt tyty ytyt tyty ytyt",
        "try yet try yet try yet try yet try yet try yet try yet",
        "ty ty ty ty ty ty ty ty ty ty ty ty ty ty ty ty"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-18",
      "title": "18. Left Top QWERT",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "q",
        "w",
        "e",
        "r",
        "t"
      ],
      "difficulty": "beginner",
      "text": "qwert trewq qwert trewq qwert trewq qwert trewq qwert trewq",
      "patterns": [
        "qwert trewq qwert trewq qwert trewq qwert trewq qwert trewq",
        "qwer wert qwer wert qwer wert qwer wert qwer wert qwer wert",
        "wert ertq wert ertq wert ertq wert ertq wert ertq wert ertq",
        "rewq qwert rewq qwert rewq qwert rewq qwert rewq qwert",
        "qwert qwert qwert qwert qwert qwert qwert qwert qwert qwert"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-19",
      "title": "19. Right Top YUIOP",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "y",
        "u",
        "i",
        "o",
        "p"
      ],
      "difficulty": "beginner",
      "text": "yuiop poiuy yuiop poiuy yuiop poiuy yuiop poiuy yuiop poiuy",
      "patterns": [
        "yuiop poiuy yuiop poiuy yuiop poiuy yuiop poiuy yuiop poiuy",
        "yuio uiop yuio uiop yuio uiop yuio uiop yuio uiop yuio uiop",
        "ioyu opyu ioyu opyu ioyu opyu ioyu opyu ioyu opyu ioyu opyu",
        "poiuy yuiop poiuy yuiop poiuy yuiop poiuy yuiop poiuy yuiop",
        "yuiop yuiop yuiop yuiop yuiop yuiop yuiop yuiop yuiop yuiop"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-20",
      "title": "20. Top Row Alternation",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "q",
        "p",
        "w",
        "o",
        "e",
        "i",
        "r",
        "u",
        "t",
        "y"
      ],
      "difficulty": "beginner",
      "text": "qp wo ei ru ty qp wo ei ru ty qp wo ei ru ty qp wo ei ru ty",
      "patterns": [
        "qp wo ei ru ty qp wo ei ru ty qp wo ei ru ty qp wo ei ru ty",
        "pq ow ie ur yt pq ow ie ur yt pq ow ie ur yt pq ow ie ur yt",
        "qw er ty ui op qw er ty ui op qw er ty ui op qw er ty ui op",
        "qe wr tu yi op qe wr tu yi op qe wr tu yi op qe wr tu yi op",
        "qr wt yu io ep qr wt yu io ep qr wt yu io ep qr wt yu io ep"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-21",
      "title": "21. Top Row Repetition",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        "u",
        "i",
        "o",
        "p"
      ],
      "difficulty": "beginner",
      "text": "qqq www eee rrr ttt qqq www eee rrr ttt qqq www eee rrr ttt",
      "patterns": [
        "qqq www eee rrr ttt qqq www eee rrr ttt qqq www eee rrr ttt",
        "yyy uuu iii ooo ppp yyy uuu iii ooo ppp yyy uuu iii ooo ppp",
        "qwert qwert qwert qwert qwert qwert qwert qwert qwert qwert",
        "yuiop yuiop yuiop yuiop yuiop yuiop yuiop yuiop yuiop yuiop",
        "trewq poiuy trewq poiuy trewq poiuy trewq poiuy trewq poiuy"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-22",
      "title": "22. Top Row Mini Words",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "t",
        "y",
        "p",
        "e",
        "w",
        "r",
        "i",
        "o",
        "u",
        "q"
      ],
      "difficulty": "beginner",
      "text": "type write power type write power type write power type write power",
      "patterns": [
        "type write power type write power type write power type write power",
        "your quiet route your quiet route your quiet route your quiet route",
        "were tire pure were tire pure were tire pure were tire pure",
        "pretty wire toy pretty wire toy pretty wire toy pretty wire toy",
        "quite row tie quite row tie quite row tie quite row tie"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-23",
      "title": "23. Top Row Word Flow",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "t",
        "y",
        "p",
        "e",
        "o",
        "u",
        "r",
        "w",
        "i",
        "g",
        "h",
        "q"
      ],
      "difficulty": "beginner",
      "text": "type your power type your power type your power type your power",
      "patterns": [
        "type your power type your power type your power type your power",
        "write it right write it right write it right write it right",
        "pretty quiet route pretty quiet route pretty quiet route",
        "your typewriter your typewriter your typewriter your typewriter",
        "we write pure we write pure we write pure we write pure"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-24",
      "title": "24. Top Row Speed Control",
      "lessonSet": "course-80",
      "section": "Top Row",
      "targetKeys": [
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        "u",
        "i",
        "o",
        "p"
      ],
      "difficulty": "beginner",
      "text": "qwert yuiop ty ru qwert yuiop ty ru qwert yuiop ty ru qwert yuiop ty ru",
      "patterns": [
        "qwert yuiop ty ru qwert yuiop ty ru qwert yuiop ty ru qwert yuiop ty ru",
        "trewq poiuy yt ur trewq poiuy yt ur trewq poiuy yt ur trewq poiuy yt ur",
        "qw er ty ui op qw er ty ui op qw er ty ui op qw er ty ui op",
        "qp wo ei ru ty qp wo ei ru ty qp wo ei ru ty qp wo ei ru ty",
        "qwerty yuiop qwerty yuiop qwerty yuiop qwerty yuiop qwerty yuiop"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Top Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-25",
      "title": "25. V & M Anchor Pair",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "v",
        "m"
      ],
      "difficulty": "beginner",
      "text": "vm mv vm mv vm mv vm mv vm mv vm mv vm mv vm mv",
      "patterns": [
        "vm mv vm mv vm mv vm mv vm mv vm mv vm mv vm mv",
        "vv mm vv mm vv mm vv mm vv mm vv mm vv mm vv mm",
        "vmvm mvmv vmvm mvmv vmvm mvmv vmvm mvmv vmvm mvmv vmvm mvmv",
        "vmmv mvv m vmmv mvv m vmmv mvv m vmmv mvv m vmmv mvv m",
        "vm vm vm vm vm vm vm vm vm vm vm vm vm vm vm vm"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-26",
      "title": "26. C & , Reach",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "c",
        ",",
        "v",
        "m"
      ],
      "difficulty": "beginner",
      "text": "c, ,c c, ,c c, ,c c, ,c c, ,c c, ,c c, ,c c, ,c",
      "patterns": [
        "c, ,c c, ,c c, ,c c, ,c c, ,c c, ,c c, ,c c, ,c",
        "cc ,, cc ,, cc ,, cc ,, cc ,, cc ,, cc ,, cc ,,",
        "c,c, ,c,c c,c, ,c,c c,c, ,c,c c,c, ,c,c c,c, ,c,c c,c, ,c,c",
        "cv,m cmvc cv,m cmvc cv,m cmvc cv,m cmvc cv,m cmvc cv,m cmvc",
        "c, c, c, c, c, c, c, c, c, c, c, c, c, c, c, c,"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-27",
      "title": "27. X & . Reach",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "x",
        ".",
        "c",
        "v",
        "m"
      ],
      "difficulty": "beginner",
      "text": "x. .x x. .x x. .x x. .x x. .x x. .x x. .x x. .x",
      "patterns": [
        "x. .x x. .x x. .x x. .x x. .x x. .x x. .x x. .x",
        "xx .. xx .. xx .. xx .. xx .. xx .. xx .. xx ..",
        "x.x. .x.x x.x. .x.x x.x. .x.x x.x. .x.x x.x. .x.x x.x. .x.x",
        "xcv. mx. xcv. mx. xcv. mx. xcv. mx. xcv. mx. xcv. mx.",
        "x. x. x. x. x. x. x. x. x. x. x. x. x. x. x. x."
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-28",
      "title": "28. Z & / Outer Keys",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "z",
        "/",
        "x",
        "c"
      ],
      "difficulty": "beginner",
      "text": "z/ /z z/ /z z/ /z z/ /z z/ /z z/ /z z/ /z z/ /z",
      "patterns": [
        "z/ /z z/ /z z/ /z z/ /z z/ /z z/ /z z/ /z z/ /z",
        "zz // zz // zz // zz // zz // zz // zz // zz //",
        "z/z/ /z/z z/z/ /z/z z/z/ /z/z z/z/ /z/z z/z/ /z/z z/z/ /z/z",
        "zx/ zxc/ zx/ zxc/ zx/ zxc/ zx/ zxc/ zx/ zxc/ zx/ zxc/",
        "z/ z/ z/ z/ z/ z/ z/ z/ z/ z/ z/ z/ z/ z/ z/ z/"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-29",
      "title": "29. B & N Center Keys",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "b",
        "n",
        "v",
        "m"
      ],
      "difficulty": "beginner",
      "text": "bn nb bn nb bn nb bn nb bn nb bn nb bn nb bn nb",
      "patterns": [
        "bn nb bn nb bn nb bn nb bn nb bn nb bn nb bn nb",
        "bb nn bb nn bb nn bb nn bb nn bb nn bb nn bb nn",
        "bnbn nbnb bnbn nbnb bnbn nbnb bnbn nbnb bnbn nbnb bnbn nbnb",
        "vbnm nm bv vbnm nm bv vbnm nm bv vbnm nm bv vbnm nm bv",
        "bn bn bn bn bn bn bn bn bn bn bn bn bn bn bn bn"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-30",
      "title": "30. Left Bottom ZXCVB",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "z",
        "x",
        "c",
        "v",
        "b"
      ],
      "difficulty": "beginner",
      "text": "zxcvb bvcxz zxcvb bvcxz zxcvb bvcxz zxcvb bvcxz zxcvb bvcxz",
      "patterns": [
        "zxcvb bvcxz zxcvb bvcxz zxcvb bvcxz zxcvb bvcxz zxcvb bvcxz",
        "zxcv xcvb zxcv xcvb zxcv xcvb zxcv xcvb zxcv xcvb zxcv xcvb",
        "cvbz bzxc cvbz bzxc cvbz bzxc cvbz bzxc cvbz bzxc cvbz bzxc",
        "bvcx zxcv bvcx zxcv bvcx zxcv bvcx zxcv bvcx zxcv bvcx zxcv",
        "zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-31",
      "title": "31. Right Bottom NM,./",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "n",
        "m",
        ",",
        ".",
        "/"
      ],
      "difficulty": "beginner",
      "text": "nm,./ /.,mn nm,./ /.,mn nm,./ /.,mn nm,./ /.,mn nm,./ /.,mn",
      "patterns": [
        "nm,./ /.,mn nm,./ /.,mn nm,./ /.,mn nm,./ /.,mn nm,./ /.,mn",
        "nm,. m,./ nm,. m,./ nm,. m,./ nm,. m,./ nm,. m,./ nm,. m,./",
        "n,m. mn,. n,m. mn,. n,m. mn,. n,m. mn,. n,m. mn,. n,m. mn,.",
        "/.,m nm,. /.,m nm,. /.,m nm,. /.,m nm,. /.,m nm,. /.,m nm,.",
        "nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-32",
      "title": "32. Bottom Row Alternation",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "z",
        "/",
        "x",
        ".",
        "c",
        ",",
        "v",
        "m",
        "b",
        "n"
      ],
      "difficulty": "beginner",
      "text": "z/ x. c, vm bn z/ x. c, vm bn z/ x. c, vm bn z/ x. c, vm bn",
      "patterns": [
        "z/ x. c, vm bn z/ x. c, vm bn z/ x. c, vm bn z/ x. c, vm bn",
        "/z .x ,c mv nb /z .x ,c mv nb /z .x ,c mv nb /z .x ,c mv nb",
        "zx cv bn m, ./ zx cv bn m, ./ zx cv bn m, ./ zx cv bn m, ./",
        "zb xn cm v, ./ zb xn cm v, ./ zb xn cm v, ./ zb xn cm v, ./",
        "zv xm cb n, ./ zv xm cb n, ./ zv xm cb n, ./ zv xm cb n, ./"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-33",
      "title": "33. Bottom Row Repetition",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "/"
      ],
      "difficulty": "beginner",
      "text": "zzz xxx ccc vvv bbb zzz xxx ccc vvv bbb zzz xxx ccc vvv bbb",
      "patterns": [
        "zzz xxx ccc vvv bbb zzz xxx ccc vvv bbb zzz xxx ccc vvv bbb",
        "nnn mmm ,,, ... /// nnn mmm ,,, ... /// nnn mmm ,,, ... ///",
        "zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb zxcvb",
        "nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./ nm,./",
        "bvcxz /.,mn bvcxz /.,mn bvcxz /.,mn bvcxz /.,mn bvcxz /.,mn"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-34",
      "title": "34. Bottom Row Mini Words",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "v",
        "a",
        "n",
        "m",
        "i",
        "x",
        "b",
        "o",
        "c",
        "z"
      ],
      "difficulty": "beginner",
      "text": "van mix box van mix box van mix box van mix box van mix box",
      "patterns": [
        "van mix box van mix box van mix box van mix box van mix box",
        "cab man zoom cab man zoom cab man zoom cab man zoom cab man zoom",
        "max ban vim max ban vim max ban vim max ban vim max ban vim",
        "comb zoom van comb zoom van comb zoom van comb zoom van",
        "box cab man box cab man box cab man box cab man box cab man"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-35",
      "title": "35. Bottom Row Word Flow",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "v",
        "a",
        "n",
        "c",
        "z",
        "o",
        "m",
        "i",
        "x",
        "b",
        "d"
      ],
      "difficulty": "beginner",
      "text": "van can zoom van can zoom van can zoom van can zoom van can zoom",
      "patterns": [
        "van can zoom van can zoom van can zoom van can zoom van can zoom",
        "mix box cab mix box cab mix box cab mix box cab mix box cab",
        "man can zoom man can zoom man can zoom man can zoom man can zoom",
        "max combo van max combo van max combo van max combo van",
        "box and van box and van box and van box and van box and van"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-36",
      "title": "36. Bottom Row Speed Control",
      "lessonSet": "course-80",
      "section": "Bottom Row",
      "targetKeys": [
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        ",",
        ".",
        "/"
      ],
      "difficulty": "beginner",
      "text": "zxcvb nm,./ bn vm zxcvb nm,./ bn vm zxcvb nm,./ bn vm zxcvb nm,./ bn vm",
      "patterns": [
        "zxcvb nm,./ bn vm zxcvb nm,./ bn vm zxcvb nm,./ bn vm zxcvb nm,./ bn vm",
        "bvcxz /.,mn nb mv bvcxz /.,mn nb mv bvcxz /.,mn nb mv bvcxz /.,mn nb mv",
        "zx cv bn m, ./ zx cv bn m, ./ zx cv bn m, ./ zx cv bn m, ./",
        "z/ x. c, vm bn z/ x. c, vm bn z/ x. c, vm bn z/ x. c, vm bn",
        "zxcvbnm,./ zxcvbnm,./ zxcvbnm,./ zxcvbnm,./ zxcvbnm,./"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Bottom Row · Pattern 1 of 5"
    },
    {
      "id": "course-80-37",
      "title": "37. Number Row 1–5",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        "1",
        "2",
        "3",
        "4",
        "5"
      ],
      "difficulty": "beginner",
      "text": "12345 54321 12345 54321 12345 54321 12345 54321 12345 54321",
      "patterns": [
        "12345 54321 12345 54321 12345 54321 12345 54321 12345 54321",
        "11223 44555 11223 44555 11223 44555 11223 44555 11223 44555",
        "13524 24135 13524 24135 13524 24135 13524 24135 13524 24135",
        "123 345 145 123 345 145 123 345 145 123 345 145 123 345 145",
        "15243 32451 15243 32451 15243 32451 15243 32451 15243 32451"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": true,
      "usesPunctuation": false,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-38",
      "title": "38. Number Row 6–0",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        "6",
        "7",
        "8",
        "9",
        "0"
      ],
      "difficulty": "beginner",
      "text": "67890 09876 67890 09876 67890 09876 67890 09876 67890 09876",
      "patterns": [
        "67890 09876 67890 09876 67890 09876 67890 09876 67890 09876",
        "66778 99000 66778 99000 66778 99000 66778 99000 66778 99000",
        "68079 70986 68079 70986 68079 70986 68079 70986 68079 70986",
        "678 890 690 678 890 690 678 890 690 678 890 690 678 890 690",
        "60789 98760 60789 98760 60789 98760 60789 98760 60789 98760"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": true,
      "usesPunctuation": false,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-39",
      "title": "39. All Numbers",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "0"
      ],
      "difficulty": "beginner",
      "text": "1234567890 1234567890 1234567890 1234567890 1234567890",
      "patterns": [
        "1234567890 1234567890 1234567890 1234567890 1234567890",
        "0987654321 0987654321 0987654321 0987654321 0987654321",
        "1357902468 1357902468 1357902468 1357902468 1357902468",
        "2468013579 2468013579 2468013579 2468013579 2468013579",
        "1029384756 1029384756 1029384756 1029384756 1029384756"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": true,
      "usesPunctuation": false,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-40",
      "title": "40. Basic Punctuation",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        ".",
        ",",
        ";",
        ":",
        "!",
        "?",
        "-",
        "_",
        "'",
        "\""
      ],
      "difficulty": "beginner",
      "text": "., ,. ., ,. ., ,. ., ,. ., ,. ., ,. ., ,. ., ,.",
      "patterns": [
        "., ,. ., ,. ., ,. ., ,. ., ,. ., ,. ., ,. ., ,.",
        ";: :; ;: :; ;: :; ;: :; ;: :; ;: :; ;: :; ;: :;",
        "!? ?! !? ?! !? ?! !? ?! !? ?! !? ?! !? ?! !? ?!",
        "-_ _- -_ _- -_ _- -_ _- -_ _- -_ _- -_ _- -_ _-",
        "'\" \"' '\" \"' '\" \"' '\" \"' '\" \"' '\" \"' '\" \"' '\" \"'"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-41",
      "title": "41. Brackets",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        "(",
        ")",
        "[",
        "]",
        "{",
        "}"
      ],
      "difficulty": "beginner",
      "text": "() () () () () () () () () () () () () () () ()",
      "patterns": [
        "() () () () () () () () () () () () () () () ()",
        "[] [] [] [] [] [] [] [] [] [] [] [] [] [] [] []",
        "{} {} {} {} {} {} {} {} {} {} {} {} {} {} {} {}",
        "([{}]) ([{}]) ([{}]) ([{}]) ([{}]) ([{}]) ([{}])",
        "{[()]} {[()]} {[()]} {[()]} {[()]} {[()]} {[()]}"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-42",
      "title": "42. Math Symbols",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        "+",
        "-",
        "=",
        "*",
        "/",
        "1",
        "0",
        "2",
        "3",
        "8",
        "7",
        "5",
        "6"
      ],
      "difficulty": "beginner",
      "text": "+- = +- = +- = +- = +- = +- = +- = +- = +- =",
      "patterns": [
        "+- = +- = +- = +- = +- = +- = +- = +- = +- =",
        "*/ +- */ +- */ +- */ +- */ +- */ +- */ +- */ +-",
        "+= -= += -= += -= += -= += -= += -= += -= += -=",
        "10+20=30 10+20=30 10+20=30 10+20=30 10+20=30 10+20=30",
        "8*7=56 8*7=56 8*7=56 8*7=56 8*7=56 8*7=56 8*7=56"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": true,
      "usesPunctuation": true,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-43",
      "title": "43. Number + Letter Basics",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        "a",
        "1",
        "s",
        "2",
        "d",
        "3",
        "f",
        "4",
        "j",
        "6",
        "k",
        "7",
        "l",
        "8",
        "p",
        "9",
        "q",
        "w",
        "e",
        "r",
        "z",
        "0",
        "x",
        "c",
        "v",
        "m",
        "5",
        "n",
        "b"
      ],
      "difficulty": "beginner",
      "text": "a1 s2 d3 f4 a1 s2 d3 f4 a1 s2 d3 f4 a1 s2 d3 f4 a1 s2 d3 f4",
      "patterns": [
        "a1 s2 d3 f4 a1 s2 d3 f4 a1 s2 d3 f4 a1 s2 d3 f4 a1 s2 d3 f4",
        "j6 k7 l8 p9 j6 k7 l8 p9 j6 k7 l8 p9 j6 k7 l8 p9 j6 k7 l8 p9",
        "q1 w2 e3 r4 q1 w2 e3 r4 q1 w2 e3 r4 q1 w2 e3 r4 q1 w2 e3 r4",
        "z0 x9 c8 v7 z0 x9 c8 v7 z0 x9 c8 v7 z0 x9 c8 v7 z0 x9 c8 v7",
        "m5 n4 b3 v2 m5 n4 b3 v2 m5 n4 b3 v2 m5 n4 b3 v2 m5 n4 b3 v2"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": true,
      "usesPunctuation": false,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-44",
      "title": "44. Basic Shift Practice",
      "lessonSet": "course-80",
      "section": "Numbers & Punctuation",
      "targetKeys": [
        "A",
        "S",
        "D",
        "F",
        "J",
        "K",
        "L",
        "P",
        "Q",
        "W",
        "E",
        "R",
        "Z",
        "X",
        "C",
        "V",
        "a",
        "s",
        "d",
        "f"
      ],
      "difficulty": "beginner",
      "text": "A S D F A S D F A S D F A S D F A S D F A S D F A S D F",
      "patterns": [
        "A S D F A S D F A S D F A S D F A S D F A S D F A S D F",
        "J K L P J K L P J K L P J K L P J K L P J K L P J K L P",
        "Q W E R Q W E R Q W E R Q W E R Q W E R Q W E R Q W E R",
        "Z X C V Z X C V Z X C V Z X C V Z X C V Z X C V Z X C V",
        "Aa Ss Dd Ff Aa Ss Dd Ff Aa Ss Dd Ff Aa Ss Dd Ff Aa Ss Dd Ff"
      ],
      "targetWpm": 8,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Numbers & Punctuation · Pattern 1 of 5"
    },
    {
      "id": "course-80-45",
      "title": "45. Home + Top Left",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "f",
        "r",
        "d",
        "e",
        "s",
        "w",
        "a",
        "q",
        "t"
      ],
      "difficulty": "intermediate",
      "text": "fr de sw aq fr de sw aq fr de sw aq fr de sw aq fr de sw aq",
      "patterns": [
        "fr de sw aq fr de sw aq fr de sw aq fr de sw aq fr de sw aq",
        "rf ed ws qa rf ed ws qa rf ed ws qa rf ed ws qa rf ed ws qa",
        "fd re sa qw fd re sa qw fd re sa qw fd re sa qw fd re sa qw",
        "ar sf de wt ar sf de wt ar sf de wt ar sf de wt ar sf de wt",
        "qf wa es dr qf wa es dr qf wa es dr qf wa es dr qf wa es dr"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-46",
      "title": "46. Home + Top Right",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "j",
        "u",
        "k",
        "i",
        "l",
        "o",
        "p",
        ";",
        "y",
        "h"
      ],
      "difficulty": "intermediate",
      "text": "ju ki lo p; ju ki lo p; ju ki lo p; ju ki lo p; ju ki lo p;",
      "patterns": [
        "ju ki lo p; ju ki lo p; ju ki lo p; ju ki lo p; ju ki lo p;",
        "uj ik ol ;p uj ik ol ;p uj ik ol ;p uj ik ol ;p uj ik ol ;p",
        "jy ku li op jy ku li op jy ku li op jy ku li op jy ku li op",
        "uh ij ok pl uh ij ok pl uh ij ok pl uh ij ok pl uh ij ok pl",
        "pj ol ik uj pj ol ik uj pj ol ik uj pj ol ik uj pj ol ik uj"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-47",
      "title": "47. Home + Bottom Left",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "f",
        "v",
        "d",
        "c",
        "s",
        "x",
        "a",
        "z",
        "b"
      ],
      "difficulty": "intermediate",
      "text": "fv dc sx az fv dc sx az fv dc sx az fv dc sx az fv dc sx az",
      "patterns": [
        "fv dc sx az fv dc sx az fv dc sx az fv dc sx az fv dc sx az",
        "vf cd xs za vf cd xs za vf cd xs za vf cd xs za vf cd xs za",
        "fb cv dx sz fb cv dx sz fb cv dx sz fb cv dx sz fb cv dx sz",
        "av sc df bx av sc df bx av sc df bx av sc df bx av sc df bx",
        "zx ca sv df zx ca sv df zx ca sv df zx ca sv df zx ca sv df"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-48",
      "title": "48. Home + Bottom Right",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "j",
        "m",
        "k",
        ",",
        "l",
        ".",
        ";",
        "/",
        "n"
      ],
      "difficulty": "intermediate",
      "text": "jm k, l. ;/ jm k, l. ;/ jm k, l. ;/ jm k, l. ;/ jm k, l. ;/",
      "patterns": [
        "jm k, l. ;/ jm k, l. ;/ jm k, l. ;/ jm k, l. ;/ jm k, l. ;/",
        "mj ,k .l /; mj ,k .l /; mj ,k .l /; mj ,k .l /; mj ,k .l /;",
        "jn km l, .; jn km l, .; jn km l, .; jn km l, .; jn km l, .;",
        "m; nk jl ,. m; nk jl ,. m; nk jl ,. m; nk jl ,. m; nk jl ,.",
        "/; .l ,k mj /; .l ,k mj /; .l ,k mj /; .l ,k mj /; .l ,k mj"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-49",
      "title": "49. Top + Bottom Left",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "r",
        "v",
        "e",
        "c",
        "w",
        "x",
        "q",
        "z",
        "t",
        "b",
        "d",
        "s"
      ],
      "difficulty": "intermediate",
      "text": "rv ec wx qz rv ec wx qz rv ec wx qz rv ec wx qz rv ec wx qz",
      "patterns": [
        "rv ec wx qz rv ec wx qz rv ec wx qz rv ec wx qz rv ec wx qz",
        "vr ce xw zq vr ce xw zq vr ce xw zq vr ce xw zq vr ce xw zq",
        "tb cv dx sz tb cv dx sz tb cv dx sz tb cv dx sz tb cv dx sz",
        "qv wc ex rb qv wc ex rb qv wc ex rb qv wc ex rb qv wc ex rb",
        "zx cq vw er zx cq vw er zx cq vw er zx cq vw er zx cq vw er"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-50",
      "title": "50. Top + Bottom Right",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "u",
        "m",
        "i",
        ",",
        "o",
        ".",
        "p",
        "/",
        "y",
        "n",
        "j",
        "k",
        "l"
      ],
      "difficulty": "intermediate",
      "text": "um i, o. p/ um i, o. p/ um i, o. p/ um i, o. p/ um i, o. p/",
      "patterns": [
        "um i, o. p/ um i, o. p/ um i, o. p/ um i, o. p/ um i, o. p/",
        "mu ,i .o /p mu ,i .o /p mu ,i .o /p mu ,i .o /p mu ,i .o /p",
        "yn uj ik ol yn uj ik ol yn uj ik ol yn uj ik ol yn uj ik ol",
        "p. o, im un p. o, im un p. o, im un p. o, im un p. o, im un",
        "/p .o ,i mu /p .o ,i mu /p .o ,i mu /p .o ,i mu /p .o ,i mu"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-51",
      "title": "51. Q-A-Z Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "q",
        "a",
        "z"
      ],
      "difficulty": "intermediate",
      "text": "qaz zaq aqz qaz zaq aqz qaz zaq aqz qaz zaq aqz qaz zaq aqz",
      "patterns": [
        "qaz zaq aqz qaz zaq aqz qaz zaq aqz qaz zaq aqz qaz zaq aqz",
        "qaza zaqa qaza zaqa qaza zaqa qaza zaqa qaza zaqa qaza zaqa",
        "qazq azqa qazq azqa qazq azqa qazq azqa qazq azqa qazq azqa",
        "zaq qaz aqz zaq qaz aqz zaq qaz aqz zaq qaz aqz zaq qaz aqz",
        "qa za aq az qa za aq az qa za aq az qa za aq az qa za aq az"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-52",
      "title": "52. W-S-X Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "w",
        "s",
        "x"
      ],
      "difficulty": "intermediate",
      "text": "wsx xsw swx wsx xsw swx wsx xsw swx wsx xsw swx wsx xsw swx",
      "patterns": [
        "wsx xsw swx wsx xsw swx wsx xsw swx wsx xsw swx wsx xsw swx",
        "wsxs xwsx wsxs xwsx wsxs xwsx wsxs xwsx wsxs xwsx wsxs xwsx",
        "swsx wsxw swsx wsxw swsx wsxw swsx wsxw swsx wsxw swsx wsxw",
        "xsw wsx swx xsw wsx swx xsw wsx swx xsw wsx swx xsw wsx swx",
        "ws sx xw sw ws sx xw sw ws sx xw sw ws sx xw sw ws sx xw sw"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-53",
      "title": "53. E-D-C Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "e",
        "d",
        "c"
      ],
      "difficulty": "intermediate",
      "text": "edc cde dec edc cde dec edc cde dec edc cde dec edc cde dec",
      "patterns": [
        "edc cde dec edc cde dec edc cde dec edc cde dec edc cde dec",
        "edcd cedc edcd cedc edcd cedc edcd cedc edcd cedc edcd cedc",
        "dced edce dced edce dced edce dced edce dced edce dced edce",
        "cde edc dec cde edc dec cde edc dec cde edc dec cde edc dec",
        "ed dc ce de ed dc ce de ed dc ce de ed dc ce de ed dc ce de"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-54",
      "title": "54. R-F-V Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "r",
        "f",
        "v"
      ],
      "difficulty": "intermediate",
      "text": "rfv vfr frv rfv vfr frv rfv vfr frv rfv vfr frv rfv vfr frv",
      "patterns": [
        "rfv vfr frv rfv vfr frv rfv vfr frv rfv vfr frv rfv vfr frv",
        "rfvf vrfv rfvf vrfv rfvf vrfv rfvf vrfv rfvf vrfv rfvf vrfv",
        "fvrf rfvr fvrf rfvr fvrf rfvr fvrf rfvr fvrf rfvr fvrf rfvr",
        "vfr rfv frv vfr rfv frv vfr rfv frv vfr rfv frv vfr rfv frv",
        "rf fv vr fr rf fv vr fr rf fv vr fr rf fv vr fr rf fv vr fr"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-55",
      "title": "55. T-G-B Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "t",
        "g",
        "b"
      ],
      "difficulty": "intermediate",
      "text": "tgb bgt gtb tgb bgt gtb tgb bgt gtb tgb bgt gtb tgb bgt gtb",
      "patterns": [
        "tgb bgt gtb tgb bgt gtb tgb bgt gtb tgb bgt gtb tgb bgt gtb",
        "tgbg btgb tgbg btgb tgbg btgb tgbg btgb tgbg btgb tgbg btgb",
        "gbtg tgbt gbtg tgbt gbtg tgbt gbtg tgbt gbtg tgbt gbtg tgbt",
        "bgt tgb gtb bgt tgb gtb bgt tgb gtb bgt tgb gtb bgt tgb gtb",
        "tg gb bt gt tg gb bt gt tg gb bt gt tg gb bt gt tg gb bt gt"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-56",
      "title": "56. Y-H-N Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "y",
        "h",
        "n"
      ],
      "difficulty": "intermediate",
      "text": "yhn nhy hyn yhn nhy hyn yhn nhy hyn yhn nhy hyn yhn nhy hyn",
      "patterns": [
        "yhn nhy hyn yhn nhy hyn yhn nhy hyn yhn nhy hyn yhn nhy hyn",
        "yhnh nyhn yhnh nyhn yhnh nyhn yhnh nyhn yhnh nyhn yhnh nyhn",
        "hnyh yhny hnyh yhny hnyh yhny hnyh yhny hnyh yhny hnyh yhny",
        "nhy yhn hyn nhy yhn hyn nhy yhn hyn nhy yhn hyn nhy yhn hyn",
        "yh hn ny hy yh hn ny hy yh hn ny hy yh hn ny hy yh hn ny hy"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-57",
      "title": "57. U-J-M Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "u",
        "j",
        "m"
      ],
      "difficulty": "intermediate",
      "text": "ujm mju jum ujm mju jum ujm mju jum ujm mju jum ujm mju jum",
      "patterns": [
        "ujm mju jum ujm mju jum ujm mju jum ujm mju jum ujm mju jum",
        "ujmj mujm ujmj mujm ujmj mujm ujmj mujm ujmj mujm ujmj mujm",
        "jmuj ujmu jmuj ujmu jmuj ujmu jmuj ujmu jmuj ujmu jmuj ujmu",
        "mju ujm jum mju ujm jum mju ujm jum mju ujm jum mju ujm jum",
        "uj jm mu ju uj jm mu ju uj jm mu ju uj jm mu ju uj jm mu ju"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-58",
      "title": "58. I-K-, Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "i",
        "k",
        ","
      ],
      "difficulty": "intermediate",
      "text": "ik, ,ki ki, ik, ,ki ki, ik, ,ki ki, ik, ,ki ki, ik, ,ki ki,",
      "patterns": [
        "ik, ,ki ki, ik, ,ki ki, ik, ,ki ki, ik, ,ki ki, ik, ,ki ki,",
        "ik,k ,ik, ik,k ,ik, ik,k ,ik, ik,k ,ik, ik,k ,ik, ik,k ,ik,",
        "k,ik ik,i k,ik ik,i k,ik ik,i k,ik ik,i k,ik ik,i k,ik ik,i",
        ",ki ik, ki, ,ki ik, ki, ,ki ik, ki, ,ki ik, ki, ,ki ik, ki,",
        "ik k, ,i ki ik k, ,i ki ik k, ,i ki ik k, ,i ki ik k, ,i ki"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-59",
      "title": "59. O-L-. Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "o",
        "l",
        "."
      ],
      "difficulty": "intermediate",
      "text": "ol. .lo lo. ol. .lo lo. ol. .lo lo. ol. .lo lo. ol. .lo lo.",
      "patterns": [
        "ol. .lo lo. ol. .lo lo. ol. .lo lo. ol. .lo lo. ol. .lo lo.",
        "ol.l .ol. ol.l .ol. ol.l .ol. ol.l .ol. ol.l .ol. ol.l .ol.",
        "l.ol ol.o l.ol ol.o l.ol ol.o l.ol ol.o l.ol ol.o l.ol ol.o",
        ".lo ol. lo. .lo ol. lo. .lo ol. lo. .lo ol. lo. .lo ol. lo.",
        "ol l. .o lo ol l. .o lo ol l. .o lo ol l. .o lo ol l. .o lo"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-60",
      "title": "60. P-;- / Column",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "p",
        ";",
        "/"
      ],
      "difficulty": "intermediate",
      "text": "p;/ /;p ;p/ p;/ /;p ;p/ p;/ /;p ;p/ p;/ /;p ;p/ p;/ /;p ;p/",
      "patterns": [
        "p;/ /;p ;p/ p;/ /;p ;p/ p;/ /;p ;p/ p;/ /;p ;p/ p;/ /;p ;p/",
        "p;/; /p;/ p;/; /p;/ p;/; /p;/ p;/; /p;/ p;/; /p;/ p;/; /p;/",
        ";/p; p;/p ;/p; p;/p ;/p; p;/p ;/p; p;/p ;/p; p;/p ;/p; p;/p",
        "/;p p;/ ;p/ /;p p;/ ;p/ /;p p;/ ;p/ /;p p;/ ;p/ /;p p;/ ;p/",
        "p; ;/ /p ;p p; ;/ /p ;p p; ;/ /p ;p p; ;/ /p ;p p; ;/ /p ;p"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-61",
      "title": "61. Alternating Hands",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "f",
        "j",
        "r",
        "u",
        "v",
        "m",
        "d",
        "k",
        "e",
        "i",
        "c",
        "n",
        "a",
        "o",
        "s",
        "w",
        "l",
        "p",
        "q",
        "y",
        "z"
      ],
      "difficulty": "intermediate",
      "text": "fj ru vm dk ei cn fj ru vm dk ei cn fj ru vm dk ei cn fj ru vm dk ei cn",
      "patterns": [
        "fj ru vm dk ei cn fj ru vm dk ei cn fj ru vm dk ei cn fj ru vm dk ei cn",
        "jf ur mv kd ie nc jf ur mv kd ie nc jf ur mv kd ie nc jf ur mv kd ie nc",
        "fa jo sw lp fa jo sw lp fa jo sw lp fa jo sw lp fa jo sw lp",
        "qr yu az nm qr yu az nm qr yu az nm qr yu az nm qr yu az nm",
        "df jk er ui df jk er ui df jk er ui df jk er ui df jk er ui"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-62",
      "title": "62. Short 3-Letter Words",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "c",
        "a",
        "t",
        "d",
        "o",
        "g",
        "s",
        "u",
        "n",
        "r",
        "f",
        "x",
        "h",
        "e",
        "y",
        "b",
        "i",
        "p",
        "m",
        "w",
        "k",
        "v"
      ],
      "difficulty": "intermediate",
      "text": "cat dog sun run fox cat dog sun run fox cat dog sun run fox",
      "patterns": [
        "cat dog sun run fox cat dog sun run fox cat dog sun run fox",
        "the and you are can the and you are can the and you are can",
        "red big top map pen red big top map pen red big top map pen",
        "sit hop win fun key sit hop win fun key sit hop win fun key",
        "day row cup van box day row cup van box day row cup van box"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-63",
      "title": "63. Common 4-Letter Words",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "t",
        "h",
        "i",
        "s",
        "a",
        "w",
        "f",
        "r",
        "o",
        "m",
        "y",
        "u",
        "v",
        "e",
        "l",
        "g",
        "d",
        "p",
        "k",
        "b",
        "n"
      ],
      "difficulty": "intermediate",
      "text": "this that with from this that with from this that with from",
      "patterns": [
        "this that with from this that with from this that with from",
        "your have will good your have will good your have will good",
        "type game play fast type game play fast type game play fast",
        "home work read book home work read book home work read book",
        "time hand word rows time hand word rows time hand word rows"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-64",
      "title": "64. Common 5-Letter Words",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "t",
        "h",
        "e",
        "r",
        "w",
        "a",
        "b",
        "o",
        "u",
        "i",
        "g",
        "f",
        "s",
        "n",
        "k",
        "l",
        "p",
        "d",
        "q",
        "c",
        "m"
      ],
      "difficulty": "intermediate",
      "text": "there where about there where about there where about there where about",
      "patterns": [
        "there where about there where about there where about there where about",
        "right first think right first think right first think right first think",
        "learn speed words learn speed words learn speed words learn speed words",
        "quick brown write quick brown write quick brown write quick brown write",
        "smart focus skill smart focus skill smart focus skill smart focus skill"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-65",
      "title": "65. Common 6+ Letter Words",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "t",
        "y",
        "p",
        "i",
        "n",
        "g",
        "l",
        "e",
        "s",
        "o",
        "k",
        "b",
        "a",
        "r",
        "d",
        "c",
        "u",
        "f",
        "m",
        "v",
        "h"
      ],
      "difficulty": "intermediate",
      "text": "typing lesson keyboard typing lesson keyboard typing lesson keyboard",
      "patterns": [
        "typing lesson keyboard typing lesson keyboard typing lesson keyboard",
        "practice accuracy practice accuracy practice accuracy practice accuracy",
        "student progress student progress student progress student progress",
        "finger movement finger movement finger movement finger movement",
        "correct rhythm correct rhythm correct rhythm correct rhythm"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-66",
      "title": "66. Word Chains",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "c",
        "a",
        "t",
        "d",
        "o",
        "g",
        "s",
        "u",
        "n",
        "r",
        "e",
        "f",
        "x",
        "b",
        "i",
        "l",
        "m",
        "v",
        "y",
        "p",
        "h",
        "w",
        "k"
      ],
      "difficulty": "intermediate",
      "text": "cat dog sun red fox cat dog sun red fox cat dog sun red fox",
      "patterns": [
        "cat dog sun red fox cat dog sun red fox cat dog sun red fox",
        "big blue box can move big blue box can move big blue box can move",
        "you can type very fast you can type very fast you can type very fast",
        "focus then type well focus then type well focus then type well",
        "hands stay on keys hands stay on keys hands stay on keys"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-67",
      "title": "67. Phrase Chains",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "k",
        "e",
        "p",
        "y",
        "o",
        "u",
        "r",
        "f",
        "i",
        "n",
        "g",
        "s",
        "a",
        "d",
        "t",
        "c",
        "h",
        "w",
        "l",
        "b",
        "x",
        "v"
      ],
      "difficulty": "intermediate",
      "text": "keep your fingers ready keep your fingers ready keep your fingers ready",
      "patterns": [
        "keep your fingers ready keep your fingers ready keep your fingers ready",
        "type each word clearly type each word clearly type each word clearly",
        "accuracy before speed accuracy before speed accuracy before speed",
        "watch the next letter watch the next letter watch the next letter",
        "use both hands evenly use both hands evenly use both hands evenly"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-68",
      "title": "68. Short Sentences",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "I",
        "c",
        "a",
        "n",
        "t",
        "y",
        "p",
        "e",
        "w",
        "i",
        "h",
        "r",
        ".",
        "T",
        "d",
        "o",
        "g",
        "u",
        "s",
        "v",
        "f",
        "Y",
        "l",
        "b",
        "K",
        "x"
      ],
      "difficulty": "intermediate",
      "text": "I can type with care. I can type with care. I can type with care.",
      "patterns": [
        "I can type with care. I can type with care. I can type with care.",
        "The dog runs very fast. The dog runs very fast. The dog runs very fast.",
        "You are doing very well. You are doing very well. You are doing very well.",
        "Typing can be great fun. Typing can be great fun. Typing can be great fun.",
        "Keep your hands relaxed. Keep your hands relaxed. Keep your hands relaxed."
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-69",
      "title": "69. Mixed Row Mastery",
      "lessonSet": "course-80",
      "section": "Mixed Rows",
      "targetKeys": [
        "q",
        "a",
        "z",
        "w",
        "s",
        "x",
        "e",
        "d",
        "c",
        "r",
        "f",
        "v",
        "t",
        "g",
        "b",
        "y",
        "h",
        "n",
        "u",
        "j",
        "m",
        "i",
        "k",
        ",",
        "o",
        "l",
        ".",
        "p",
        ";",
        "/"
      ],
      "difficulty": "intermediate",
      "text": "qaz wsx edc rfv tgb qaz wsx edc rfv tgb qaz wsx edc rfv tgb",
      "patterns": [
        "qaz wsx edc rfv tgb qaz wsx edc rfv tgb qaz wsx edc rfv tgb",
        "yhn ujm ik, ol. p;/ yhn ujm ik, ol. p;/ yhn ujm ik, ol. p;/",
        "asdf qwert zxcvb asdf qwert zxcvb asdf qwert zxcvb asdf qwert zxcvb",
        "jkl; yuiop nm,./ jkl; yuiop nm,./ jkl; yuiop nm,./ jkl; yuiop nm,./",
        "type fast with control type fast with control type fast with control"
      ],
      "targetWpm": 15,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Mixed Rows · Pattern 1 of 5"
    },
    {
      "id": "course-80-70",
      "title": "70. Same-Finger Stretches",
      "lessonSet": "course-80",
      "section": "Difficult",
      "targetKeys": [
        "f",
        "r",
        "t",
        "d",
        "e",
        "c",
        "j",
        "u",
        "m",
        "k",
        "i",
        "a",
        "q",
        "z",
        "w",
        "s",
        "x",
        "v",
        "g",
        "b",
        "y",
        "h",
        "n",
        ",",
        "o",
        "l",
        ".",
        "p",
        ";",
        "/"
      ],
      "difficulty": "advanced",
      "text": "frft dedc jumu kiki frft dedc jumu kiki frft dedc jumu kiki",
      "patterns": [
        "frft dedc jumu kiki frft dedc jumu kiki frft dedc jumu kiki",
        "aqaz wsxw edce aqaz wsxw edce aqaz wsxw edce aqaz wsxw edce",
        "rfvr tgbt yhny rfvr tgbt yhny rfvr tgbt yhny rfvr tgbt yhny",
        "ujmu ik,i ol.o ujmu ik,i ol.o ujmu ik,i ol.o ujmu ik,i ol.o",
        "p;/p azqa xswx p;/p azqa xswx p;/p azqa xswx p;/p azqa xswx"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Difficult · Pattern 1 of 5"
    },
    {
      "id": "course-80-71",
      "title": "71. Rapid Alternation",
      "lessonSet": "course-80",
      "section": "Difficult",
      "targetKeys": [
        "f",
        "j",
        "d",
        "k",
        "r",
        "u",
        "t",
        "y",
        "v",
        "m",
        "b",
        "n",
        "q",
        "p",
        "s",
        "l",
        "e",
        "i",
        "x",
        ".",
        "a",
        ";",
        "w",
        "o",
        "c",
        ",",
        "g",
        "h"
      ],
      "difficulty": "advanced",
      "text": "fjfj dkdk ruru tyty fjfj dkdk ruru tyty fjfj dkdk ruru tyty",
      "patterns": [
        "fjfj dkdk ruru tyty fjfj dkdk ruru tyty fjfj dkdk ruru tyty",
        "vmvm bnbn qpq p vmvm bnbn qpq p vmvm bnbn qpq p vmvm bnbn qpq p",
        "slsl eiei x.x. slsl eiei x.x. slsl eiei x.x. slsl eiei x.x.",
        "a;a; wo wo c,c, a;a; wo wo c,c, a;a; wo wo c,c, a;a; wo wo c,c,",
        "tyty gbg bnhn tyty gbg bnhn tyty gbg bnhn tyty gbg bnhn"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Difficult · Pattern 1 of 5"
    },
    {
      "id": "course-80-72",
      "title": "72. Repeated Letters",
      "lessonSet": "course-80",
      "section": "Difficult",
      "targetKeys": [
        "f",
        "j",
        "e",
        "t",
        "s",
        "l",
        "r",
        "u",
        "a",
        ";",
        "q",
        "p",
        "z",
        "/",
        "x",
        ".",
        "c",
        ",",
        "v",
        "m"
      ],
      "difficulty": "advanced",
      "text": "ffff jjjj eeee tttt ffff jjjj eeee tttt ffff jjjj eeee tttt",
      "patterns": [
        "ffff jjjj eeee tttt ffff jjjj eeee tttt ffff jjjj eeee tttt",
        "ssss llll rrrr uuuu ssss llll rrrr uuuu ssss llll rrrr uuuu",
        "aaaa ;;;; qqqq pppp aaaa ;;;; qqqq pppp aaaa ;;;; qqqq pppp",
        "zzzz //// xxxx .... zzzz //// xxxx .... zzzz //// xxxx ....",
        "cccc ,,,, vvvv mmmm cccc ,,,, vvvv mmmm cccc ,,,, vvvv mmmm"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Difficult · Pattern 1 of 5"
    },
    {
      "id": "course-80-73",
      "title": "73. Tricky Words",
      "lessonSet": "course-80",
      "section": "Difficult",
      "targetKeys": [
        "m",
        "i",
        "n",
        "u",
        "r",
        "h",
        "y",
        "t",
        "p",
        "e",
        "o",
        "l",
        "q",
        "a",
        "w",
        "k",
        "d",
        "z",
        "s",
        "c"
      ],
      "difficulty": "advanced",
      "text": "minimum rhythm people little minimum rhythm people little",
      "patterns": [
        "minimum rhythm people little minimum rhythm people little",
        "queue awkward puzzle queue awkward puzzle queue awkward puzzle",
        "mississippi success mississippi success mississippi success",
        "parallel committee parallel committee parallel committee",
        "necessary occurrence necessary occurrence necessary occurrence"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Difficult · Pattern 1 of 5"
    },
    {
      "id": "course-80-74",
      "title": "74. Long Words",
      "lessonSet": "course-80",
      "section": "Difficult",
      "targetKeys": [
        "k",
        "e",
        "y",
        "b",
        "o",
        "a",
        "r",
        "d",
        "p",
        "c",
        "t",
        "i",
        "m",
        "u",
        "l",
        "n",
        "g",
        "h",
        "v",
        "s"
      ],
      "difficulty": "advanced",
      "text": "keyboard practice computer accuracy keyboard practice computer accuracy",
      "patterns": [
        "keyboard practice computer accuracy keyboard practice computer accuracy",
        "learning challenge development learning challenge development",
        "concentration improvement concentration improvement concentration improvement",
        "coordination discipline coordination discipline coordination discipline",
        "responsibility communication responsibility communication"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Difficult · Pattern 1 of 5"
    },
    {
      "id": "course-80-75",
      "title": "75. Capitalization",
      "lessonSet": "course-80",
      "section": "Complex",
      "targetKeys": [
        "H",
        "e",
        "l",
        "o",
        "W",
        "r",
        "d",
        "T",
        "y",
        "p",
        "i",
        "n",
        "g",
        "P",
        "a",
        "c",
        "t",
        "Q",
        "u",
        "k",
        "B",
        "w",
        "F",
        "x",
        "J",
        "m",
        "s",
        "h",
        "E",
        "v",
        "S",
        "C",
        "I",
        "U",
        "f",
        "L",
        "N"
      ],
      "difficulty": "expert",
      "text": "Hello World Typing Practice Hello World Typing Practice Hello World Typing Practice",
      "patterns": [
        "Hello World Typing Practice Hello World Typing Practice Hello World Typing Practice",
        "Quick Brown Fox Jumps High Quick Brown Fox Jumps High Quick Brown Fox Jumps High",
        "Every Student Can Improve Every Student Can Improve Every Student Can Improve",
        "Use Shift With Control Use Shift With Control Use Shift With Control",
        "Capital Letters Need Care Capital Letters Need Care Capital Letters Need Care"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": false,
      "usesPunctuation": false,
      "instruction": "Complex · Pattern 1 of 5"
    },
    {
      "id": "course-80-76",
      "title": "76. Numbers in Text",
      "lessonSet": "course-80",
      "section": "Complex",
      "targetKeys": [
        "L",
        "e",
        "s",
        "o",
        "n",
        "1",
        "t",
        "a",
        "r",
        "8",
        "d",
        "0",
        "T",
        "y",
        "p",
        "2",
        "5",
        "w",
        "i",
        "6",
        "c",
        "v",
        "l",
        "h",
        "k",
        "S",
        "9",
        "u",
        "f",
        "P",
        "m"
      ],
      "difficulty": "expert",
      "text": "Lesson 1 starts at 8 and ends at 10 Lesson 1 starts at 8 and ends at 10",
      "patterns": [
        "Lesson 1 starts at 8 and ends at 10 Lesson 1 starts at 8 and ends at 10",
        "Type 25 words in 60 seconds Type 25 words in 60 seconds Type 25 words in 60 seconds",
        "Level 12 has 5 new tasks Level 12 has 5 new tasks Level 12 has 5 new tasks",
        "Score 95 out of 100 today Score 95 out of 100 today Score 95 out of 100 today",
        "Practice 20 minutes daily Practice 20 minutes daily Practice 20 minutes daily"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": true,
      "usesPunctuation": false,
      "instruction": "Complex · Pattern 1 of 5"
    },
    {
      "id": "course-80-77",
      "title": "77. Letters + Numbers",
      "lessonSet": "course-80",
      "section": "Complex",
      "targetKeys": [
        "a",
        "b",
        "c",
        "1",
        "2",
        "3",
        "t",
        "y",
        "p",
        "e",
        "0",
        "g",
        "m",
        "9",
        "l",
        "v",
        "u",
        "s",
        "r",
        "5",
        "k",
        "o",
        "4",
        "q",
        "w",
        "6",
        "z",
        "x",
        "8",
        "7",
        "n",
        "i",
        "d"
      ],
      "difficulty": "expert",
      "text": "abc123 type20 game99 level10 abc123 type20 game99 level10",
      "patterns": [
        "abc123 type20 game99 level10 abc123 type20 game99 level10",
        "user25 key123 room404 user25 key123 room404 user25 key123 room404",
        "q1w2e3 r4t5y6 q1w2e3 r4t5y6 q1w2e3 r4t5y6 q1w2e3 r4t5y6",
        "z9x8c7 v6b5n4 z9x8c7 v6b5n4 z9x8c7 v6b5n4 z9x8c7 v6b5n4",
        "mix2026 code101 test500 mix2026 code101 test500 mix2026 code101 test500"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": false,
      "usesNumbers": true,
      "usesPunctuation": false,
      "instruction": "Complex · Pattern 1 of 5"
    },
    {
      "id": "course-80-78",
      "title": "78. Symbols",
      "lessonSet": "course-80",
      "section": "Complex",
      "targetKeys": [
        "!",
        "@",
        "#",
        "$",
        "%",
        "&",
        "*",
        "(",
        ")",
        "?",
        "/",
        ":",
        ";",
        ".",
        ",",
        "<",
        ">",
        "+",
        "-",
        "=",
        "_",
        "[",
        "]",
        "{",
        "}",
        "e",
        "m",
        "a",
        "i",
        "l",
        "t",
        "s",
        "c",
        "o",
        "p",
        "b",
        "x",
        "y",
        "z",
        "u",
        "d",
        "h",
        "n",
        "r"
      ],
      "difficulty": "expert",
      "text": "!@#$% &*() ?/:; .,<> !@#$% &*() ?/:; .,<> !@#$% &*() ?/:; .,<>",
      "patterns": [
        "!@#$% &*() ?/:; .,<> !@#$% &*() ?/:; .,<> !@#$% &*() ?/:; .,<>",
        "+-=_ []{} ()<> +-=_ []{} ()<> +-=_ []{} ()<> +-=_ []{} ()<>",
        "email@test.com #topic email@test.com #topic email@test.com #topic",
        "a+b=c; x/y=z? a+b=c; x/y=z? a+b=c; x/y=z? a+b=c; x/y=z?",
        "use_dash-and_under_score use_dash-and_under_score use_dash-and_under_score"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": false,
      "usesPunctuation": true,
      "instruction": "Complex · Pattern 1 of 5"
    },
    {
      "id": "course-80-79",
      "title": "79. Mixed Characters",
      "lessonSet": "course-80",
      "section": "Complex",
      "targetKeys": [
        "A",
        "b",
        "c",
        "@",
        "1",
        "2",
        "3",
        "G",
        "a",
        "m",
        "e",
        "#",
        "5",
        "T",
        "y",
        "p",
        "!",
        "9",
        "K",
        "_",
        "0",
        "6",
        "U",
        "s",
        "r",
        "-",
        "4",
        "S",
        "o",
        "=",
        "8",
        "+",
        "B",
        "C",
        "n",
        "d",
        "X",
        "/",
        "Y",
        "Z",
        "i",
        "l",
        ".",
        "P",
        "L",
        "v"
      ],
      "difficulty": "expert",
      "text": "Abc@123 Game#25 Type!99 Abc@123 Game#25 Type!99 Abc@123 Game#25 Type!99",
      "patterns": [
        "Abc@123 Game#25 Type!99 Abc@123 Game#25 Type!99 Abc@123 Game#25 Type!99",
        "Key_2026 User-45 Score=98 Key_2026 User-45 Score=98 Key_2026 User-45 Score=98",
        "A+B=C and X/Y=Z A+B=C and X/Y=Z A+B=C and X/Y=Z A+B=C and X/Y=Z",
        "name@email.com id#101 name@email.com id#101 name@email.com id#101",
        "Pass@2026 Level!80 Pass@2026 Level!80 Pass@2026 Level!80"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": true,
      "usesPunctuation": true,
      "instruction": "Complex · Pattern 1 of 5"
    },
    {
      "id": "course-80-80",
      "title": "80. Master Challenge",
      "lessonSet": "course-80",
      "section": "Complex",
      "targetKeys": [
        "T",
        "h",
        "e",
        "q",
        "u",
        "i",
        "c",
        "k",
        "b",
        "r",
        "o",
        "w",
        "n",
        "f",
        "x",
        "j",
        "m",
        "p",
        "s",
        "v",
        "t",
        "l",
        "a",
        "z",
        "y",
        "d",
        "g",
        ".",
        "1",
        "2",
        "3",
        "!",
        "P",
        "C",
        "?",
        "L",
        "-",
        "8",
        "0",
        ":",
        "M"
      ],
      "difficulty": "expert",
      "text": "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.",
      "patterns": [
        "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.",
        "Typing 123 is fun when accuracy comes first! Typing 123 is fun when accuracy comes first!",
        "Practice makes typing easier every single day. Practice makes typing easier every single day.",
        "Can you type this sentence correctly and quickly? Can you type this sentence correctly and quickly?",
        "Level-80: Master Typist challenge starts now! Level-80: Master Typist challenge starts now!"
      ],
      "targetWpm": 20,
      "targetAccuracy": 92,
      "needsShift": true,
      "usesNumbers": true,
      "usesPunctuation": true,
      "instruction": "Complex · Pattern 1 of 5"
    }
  ]
};
